# Lab 06 - Bài tập

In [16]:
# import library
import pandas as pd
import numpy as np
import scipy.stats as stats
! pip install xlrd

Requirement already satisfied: xlrd in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.0.1)

## <u>Bài 1</u>

Green M&M Candies liên quan đến Dataset 18 trong file excel. Tìm tỉ lệ mẫu của M&M có màu xanh lá cây (green). Sử dụng kết quả để xây dựng 1 ước lượng khoảng tin cậy 95% của tổng thể M&M có màu xanh.

In [20]:
df_M_M = pd.read_excel('18_M_M.xls')
df_M_M

      Red  Orange  Yellow  Brown   Blue  Green
0   0.751   0.735   0.883  0.696  0.881  0.925
1   0.841   0.895   0.769  0.876  0.863  0.914
2   0.856   0.865   0.859  0.855  0.775  0.881
3   0.799   0.864   0.784  0.806  0.854  0.865
4   0.966   0.852   0.824  0.840  0.810  0.865
5   0.859   0.866   0.858  0.868  0.858  1.015
6   0.857   0.859   0.848  0.859  0.818  0.876
7   0.942   0.838   0.851  0.982  0.868  0.809
8   0.873   0.863     NaN    NaN  0.803  0.865
9   0.809   0.888     NaN    NaN  0.932  0.848
10  0.890   0.925     NaN    NaN  0.842  0.940
11  0.878   0.793     NaN    NaN  0.832  0.833
12  0.905   0.977     NaN    NaN  0.807  0.845
13    NaN   0.850     NaN    NaN  0.841  0.852
14    NaN   0.830     NaN    NaN  0.932  0.778
15    NaN   0.856     NaN    NaN  0.833  0.814
16    NaN   0.842     NaN    NaN  0.881  0.791
17    NaN   0.778     NaN    NaN  0.818  0.810
18    NaN   0.786     NaN    NaN  0.864  0.881
19    NaN   0.853     NaN    NaN  0.825    NaN
20    NaN   0.864     NaN    NaN  0.855    NaN
21    NaN   0.873     NaN    NaN  0.942    NaN
22    NaN   0.880     NaN    NaN  0.825    NaN
23    NaN   0.882     NaN    NaN  0.869    NaN
24    NaN   0.931     NaN    NaN  0.912    NaN
25    NaN     NaN     NaN    NaN  0.887    NaN
26    NaN     NaN     NaN    NaN  0.886    NaN

In [25]:
# Count the number of green candies
green_count = df_M_M['Green'].count()
print(green_count)

# Calculate the sample proportion
sample_proportion = green_count / len(df_M_M)

# Calculate the standard error
standard_error = np.sqrt(sample_proportion * (1 - sample_proportion) / len(df_M_M))

# Calculate the margin of error
margin_of_error = 1.96 * standard_error

# Calculate the lower and upper bounds of the confidence interval
lower_bound = sample_proportion - margin_of_error
upper_bound = sample_proportion + margin_of_error

# Print the sample proportion and confidence interval
print("Sample Proportion:", sample_proportion)
print("Confidence Interval (95%):", (lower_bound, upper_bound))

19
Sample Proportion: 0.7037037037037037
Confidence Interval (95%): (0.5314644166750504, 0.875942990732357)

## <u>Bài 2</u>

Freshman Weight Gain liên quan đến Dataset 3 trong file excel

a. Dựa vào kết quả của mẫu, tìm ước lượng điểm tốt nhất của tỉ lệ phần trăm các sinh viên cao đẳng tăng cân trong năm thứ 1.

b. Xây dựng ước lượng khoảng tin cậy 95% về tỉ lệ phần trăm các sinh viên cao đẳng tăng cân trong năm thứ 1.

In [24]:
df_fresh = pd.read_excel('03_FRESH15.xls')
df_fresh

   SEX  WTSEP  WTAPR  BMISP  BMIAP
0    M     72     59  22.02  18.14
1    M     97     86  19.70  17.44
2    M     74     69  24.09  22.43
3    M     93     88  26.97  25.57
4    F     68     64  21.51  20.10
..  ..    ...    ...    ...    ...
62   M     65     71  22.51  24.45
63   M     75     82  23.69  25.80
64   F     42     49  15.08  17.74
65   M     74     82  22.64  25.33
66   M     94    105  36.57  40.86

[67 rows x 5 columns]

In [40]:
best_estimate = df_fresh['WTAPR'].mean()
best_estimate

66.23880597014926

## <u>Bài 3</u>

Lượng mưa ở Boston: liên quan đến Dataset 14 trong file excel, và quan tâm đến các ngày với các giá trị lượng mưa khác nhau từ 0 đến các ngày có mưa có giá trị lượng mưa lớn hơn 0.

- Xây dựng ước lượng khoảng tin cậy 95% cho tỉ lệ mưa trong các ngày Thứ Tư và 
- Xây dựng ước lượng khoảng tin cậy 95% cho tỉ lệ mưa trong các ngày Chủ Nhật.

In [36]:
df_bostrain= pd.read_excel('14_BOSTRAIN.xls')
df_bostrain

     MON  TUES   WED  THURS   FRI   SAT   SUN
0   0.00  0.00  0.00   0.04  0.04  0.00  0.05
1   0.00  0.00  0.00   0.06  0.03  0.10  0.00
2   0.00  0.00  0.00   0.71  0.00  0.00  0.00
3   0.00  0.44  0.14   0.04  0.04  0.64  0.00
4   0.05  0.00  0.00   0.00  0.01  0.05  0.00
5   0.00  0.00  0.64   0.00  0.00  0.00  0.00
6   0.01  0.00  0.00   0.00  0.30  0.05  0.00
7   0.00  0.00  0.01   0.00  0.00  0.00  0.00
8   0.00  0.01  0.01   0.16  0.00  0.00  0.09
9   0.12  0.06  0.18   0.39  0.00  0.10  0.00
10  0.00  0.00  0.00   0.00  0.78  0.49  0.00
11  0.00  0.02  0.00   0.00  0.01  0.17  0.00
12  1.41  0.65  0.31   0.00  0.00  0.54  0.00
13  0.00  0.00  0.00   0.00  0.00  0.00  0.00
14  0.00  0.00  0.00   0.00  0.00  0.40  0.28
15  0.00  0.00  0.00   0.30  0.87  0.49  0.00
16  0.47  0.00  0.00   0.00  0.00  0.00  0.00
17  0.00  0.09  0.00   0.24  0.00  0.05  0.00
18  0.00  0.14  0.00   0.00  0.04  0.07  0.00
19  0.92  0.36  0.02   0.09  0.27  0.00  0.00
20  0.01  0.00  0.06   0.00  0.00  0.00  0.27
21  0.01  0.00  0.00   0.00  0.00  0.00  0.01
22  0.00  0.00  0.00   0.00  0.00  0.00  0.00
23  0.00  0.00  0.00   0.00  0.71  0.00  0.00
24  0.00  0.00  0.27   0.08  0.00  0.00  0.33
25  0.00  0.00  0.00   0.00  0.00  0.00  0.00
26  0.03  0.00  0.08   0.14  0.00  0.00  0.00
27  0.00  0.11  0.06   0.02  0.00  0.00  0.00
28  0.01  0.05  0.00   0.01  0.00  0.00  0.00
29  0.00  0.00  0.00   0.00  0.12  0.00  0.00
30  0.11  0.03  0.00   0.00  0.00  0.00  0.44
31  0.01  0.01  0.00   0.00  0.11  0.18  0.00
32  0.49  0.00  0.64   0.01  0.00  0.00  0.01
33  0.00  0.00  0.08   0.85  0.01  0.00  0.00
34  0.01  0.02  0.00   0.00  0.03  0.00  0.00
35  0.00  0.00  0.12   0.00  0.00  0.00  0.00
36  0.00  0.00  0.01   0.04  0.26  0.04  0.00
37  0.00  0.00  0.00   0.00  0.00  0.40  0.00
38  0.12  0.00  0.00   0.00  0.00  0.00  0.00
39  0.00  0.00  0.00   0.00  0.24  0.00  0.23
40  0.00  0.00  0.00   0.02  0.00  0.00  0.00
41  0.00  0.00  0.00   0.02  0.00  0.00  0.00
42  0.59  0.00  0.00   0.00  0.00  0.68  0.00
43  0.00  0.01  0.00   0.00  0.00  1.48  0.21
44  0.01  0.00  0.00   0.00  0.05  0.69  1.28
45  0.00  0.00  0.00   0.00  0.96  0.00  0.01
46  0.00  0.00  0.00   0.00  0.00  0.79  0.02
47  0.41  0.00  0.06   0.01  0.00  0.00  0.28
48  0.00  0.00  0.00   0.08  0.04  0.00  0.00
49  0.00  0.00  0.00   0.00  0.00  0.00  0.00
50  0.00  0.74  0.00   0.00  0.00  0.00  0.00
51  0.43  0.30  0.00   0.26  0.00  0.02  0.01
52   NaN   NaN  0.00    NaN   NaN   NaN   NaN

In [37]:
# Calculate the proportion of rain on Wednesdays
wednesday_rain_proportion = df_bostrain['WED'].mean()

# Calculate the sample size
sample_size = len(df_bostrain)

# Calculate the standard error
standard_error = np.sqrt(wednesday_rain_proportion * (1 - wednesday_rain_proportion) / sample_size)

# Calculate the margin of error
margin_of_error = 1.96 * standard_error

# Calculate the lower and upper bounds of the confidence interval
lower_bound = wednesday_rain_proportion - margin_of_error
upper_bound = wednesday_rain_proportion + margin_of_error

# Print the confidence interval
print("Confidence Interval (95%):", (lower_bound, upper_bound))

Confidence Interval (95%): (-0.008339579348793182, 0.10984901331105734)

In [39]:
sunday_rain_proportion = df_bostrain['SUN'].mean()
sample_size = len(df_bostrain)

standard_error = np.sqrt(sunday_rain_proportion * (1 - sunday_rain_proportion) / sample_size)
margin_of_error = 1.96 * standard_error

lower_bound = sunday_rain_proportion - margin_of_error
upper_bound = sunday_rain_proportion + margin_of_error

(lower_bound, upper_bound)

(5.794061690182761e-05, 0.13532667476771354)

## <u>Bài 4</u>

Tổng số tiền phim: liên quan đến Dataset 9 trong file excel. Xây dựng ước tính khoảng thời gian tin cậy 95% của tổng số tiền trung bình cho quần thể của tất cả các phim. Giả định rằng độ lệch chuẩn của quần thể được biết là 100 triệu đô la.

In [30]:
df_movies = pd.read_excel('09_MOVIES.xls')
df_movies

,Title,MPAA,Budget,Gross,Length,Rating
0,8 Mile,R,41.0,117,110,6.7
1,Alone in the Dark,R,20.0,5,96,2.2
2,Aviator,PG-13,116.0,103,170,7.6
3,Big Fish,PG-13,70.0,66,125,8.0
4,Bourne Identity,PG-13,75.0,121,119,7.4
5,Break-Up,PG-13,52.0,116,105,5.8
6,Charlie's Angels: Full Throttle,PG-13,120.0,101,106,4.8
7,Collateral,R,65.0,100,120,7.7
8,Crash,R,6.5,55,113,8.3
9,Daddy Day Care,PG,60.0,104,92,5.7
10,DaVinci Code,PG-13,125.0,213,149,6.5
11,Eternal Sunshine of the Spotless Mind,R,20.0,34,108,8.6
12,From Justin to Kelly,PG,5.0,12,81,1.9
13,Harry Potter Goblet of Fire,PG-13,150.0,290,157,7.8
14,Hostel,R,4.5,47,94,5.8
15,House of the Dead,R,7.0,10,90,2.0
16,Last Samurai,R,100.0,111,154,7.8
17,Million Dollar Baby,PG-13,30.0,100,132,8.4
18,Pirates of the Carribbean (II),PG-13,225.0,322,150,7.5
19,Rollerball,PG-13,70.0,19,97,2.7
20,S.W.A.T.,PG-13,80.0,117,117,6.0
21,Secret Window,PG-13,40.0,48,96,6.3
22,Signs,PG-13,70.0,228,106,7.0
23,Silent Hill,R,50.0,47,127,6.6
24,Son of the Mask,PG,74.0,17,94,2.0
25,Spider-Man 2,PG-13,200.0,373,127,7.8
26,Star Wars III,PG-13,113.0,380,140,8.0
27,Sum of All Fears,PG-13,68.0,118,124,6.4
28,The Pianist,R,35.0,33,150,8.5
29,The Village,PG-13,72.0,114,108,6.6
30,Van Helsing,PG-13,160.0,120,132,5.3
31,Vanilla Sky,R,68.0,101,136,6.8
32,Walk the Line,PG-13,29.0,120,136,8.1
33,War of the Worlds,PG-13,132.0,234,116,6.7
34,Wedding Crashers,R,40.0,209,119,7.3

In [29]:

sample_mean = df_movies['Gross'].mean()
sample_size = len(df_movies)
population_std = 100

z = stats.norm.ppf(0.975)  # 95% confidence level, two-tailed test

margin_of_error = z * (population_std / (sample_size ** 0.5))

lower_bound = sample_mean - margin_of_error
upper_bound = sample_mean + margin_of_error

(lower_bound, upper_bound)

(89.87056198702633, 156.12943801297365)

## <u>Bài 5</u>

Điểm đánh giá tín dụng FICO: liên quan đến Dataset 24 trong file excel. Xây dựng ước lượng khoảng tin cậy 99% của điểm FICO trung bình cho quần thể. Giả sử độ lệch chuẩn của quần thể là 92,2.

In [31]:
df_fico = pd.read_excel('24_FICO.xls')
df_fico

    708
0   713
1   781
2   809
3   797
4   793
..  ...
94  796
95  611
96  709
97  697
98  732

[99 rows x 1 columns]

In [35]:
sample_mean = df_fico.mean()
sample_size = len(df_fico)
population_std = 92.2

z = stats.norm.ppf(0.995)  # 99% confidence level, two-tailed test

margin_of_error = z * (population_std / (sample_size ** 0.5))

lower_bound = sample_mean - margin_of_error
upper_bound = sample_mean + margin_of_error

(lower_bound, upper_bound)

(708    679.191816
 dtype: float64,
 708    726.929396
 dtype: float64)